services:
  - type: web
    name: imbatido
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: MONGODB_URI
        sync: false
      - key: AI_API_KEY
        sync: false
